parameters:
#    application_main.example.class: Application\MainBundle\Example

services:
#    application_main.example:
#        class: %application_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
